import script01 from './modules/script-01.js';
import script02 from './modules/script-02.js';
import script03 from './modules/script-03.js';
import script04 from './modules/script-04.js';
import script05 from './modules/script-05.js';
import script06 from './modules/script-06.js';
import script07 from './modules/script-07.js';
import script08 from './modules/script-08.js';
import script09 from './modules/script-09.js';
import script10 from './modules/script-10.js';
import script11 from './modules/script-11.js';
import script12 from './modules/script-12.js';
import script13 from './modules/script-13.js';
import script14 from './modules/script-14.js';
import script15 from './modules/script-15.js';
import script16 from './modules/script-16.js';

// script01();
// script02();
// script03();
// script04();
// script05();
// script06();
// script07();
// script08();
// script09();
// script10();
// script11();
// script12();
// script13();
// script14();
// script15();
// script16();
